plugins {
    id 'com.android.application'
}

android {
    namespace 'com.explapp.cardashcam'
    compileSdk 35

    defaultConfig {
        applicationId 'com.explapp.cardashcam'
        minSdk 19
        targetSdk 28
        versionCode 6
        versionName '2.1.0-android-4.4'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}
